// src/frontend/svelte/components/EmptyState.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  type SuggestionCategory = {
    icon: string;
    label: string;
    prompts: string[];
  };

  type EmptyStateProps = {
    inputBox: Snippet;
    onSendMessage: (text: string) => void;
    suggestions: SuggestionCategory[];
  };

  let { inputBox, onSendMessage, suggestions }: EmptyStateProps = $props();

  let activeCategory = $state<string | null>(null);

  let activeSuggestions = $derived(
    suggestions.find((cat) => cat.label === activeCategory),
  );
</script>

<div class="empty-state">
  <p class="welcome-text">What can I help you with?</p>
  {@render inputBox()}
  <div class="suggestions">
    <div class="suggestion-pills">
      {#each suggestions as cat (cat.label)}
        <button
          class="suggestion-pill"
          class:active={activeCategory === cat.label}
          onclick={() =>
            (activeCategory = activeCategory === cat.label ? null : cat.label)}
          type="button"
        >
          <svg
            fill="none"
            height="14"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            width="14"
          >
            <path d={cat.icon} />
          </svg>
          {cat.label}
        </button>
      {/each}
    </div>
    {#if activeSuggestions}
      <div class="suggestion-prompts">
        {#each activeSuggestions.prompts as prompt (prompt)}
          <button
            class="suggestion"
            onclick={() => onSendMessage(prompt)}
            type="button"
          >
            {prompt}
          </button>
        {/each}
      </div>
    {/if}
  </div>
</div>

// src/frontend/react/components/EmptyState.tsx
import { useState, type ReactNode } from "react";

type SuggestionCategory = {
  icon: string;
  label: string;
  prompts: string[];
};

type EmptyStateProps = {
  inputBox: ReactNode;
  onSendMessage: (text: string) => void;
  suggestions: SuggestionCategory[];
};

export const EmptyState = ({
  inputBox,
  onSendMessage,
  suggestions,
}: EmptyStateProps) => {
  const [activeCategory, setActiveCategory] = useState<string | null>(null);

  const activeSuggestions = suggestions.find(
    (cat) => cat.label === activeCategory,
  );

  return (
    <div className="empty-state">
      <p className="welcome-text">What can I help you with?</p>
      {inputBox}
      <div className="suggestions">
        <SuggestionPills
          activeCategory={activeCategory}
          onSelect={setActiveCategory}
          suggestions={suggestions}
        />
        {activeSuggestions && (
          <div className="suggestion-prompts">
            {activeSuggestions.prompts.map((prompt) => (
              <button
                className="suggestion"
                key={prompt}
                onClick={() => onSendMessage(prompt)}
                type="button"
              >
                {prompt}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

type SuggestionPillsProps = {
  activeCategory: string | null;
  onSelect: (label: string | null) => void;
  suggestions: SuggestionCategory[];
};

const SuggestionPills = ({
  activeCategory,
  onSelect,
  suggestions,
}: SuggestionPillsProps) => (
  <div className="suggestion-pills">
    {suggestions.map((cat) => (
      <button
        className={`suggestion-pill ${activeCategory === cat.label ? "active" : ""}`}
        key={cat.label}
        onClick={() =>
          onSelect(activeCategory === cat.label ? null : cat.label)
        }
        type="button"
      >
        <svg
          fill="none"
          height="14"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          viewBox="0 0 24 24"
          width="14"
        >
          <path d={cat.icon} />
        </svg>
        {cat.label}
      </button>
    ))}
  </div>
);
