// src/frontend/svelte/components/ModelListItem.svelte
<script lang="ts">
  import { COST_LABELS, COST_COLORS, type ModelDef } from "../../models";
  import CapabilityIcon from "./CapabilityIcon.svelte";

  type ModelListItemProps = {
    model: ModelDef;
    onclick: () => void;
    providerLogoPath: string;
    selected: boolean;
  };

  let { model, onclick, providerLogoPath, selected }: ModelListItemProps =
    $props();
</script>

<button class="picker-model" class:selected {onclick} type="button">
  <div class="picker-model-row">
    <img
      alt=""
      class="picker-model-logo"
      height="16"
      src="{providerLogoPath}/{model.provider}.svg"
      width="16"
    />
    <span class="picker-model-name">{model.name}</span>
    <span class="picker-cost" style="color:{COST_COLORS[model.cost]}"
      >{COST_LABELS[model.cost]}</span
    >
    {#if model.legacy}
      <span class="picker-legacy">legacy</span>
    {/if}
    <div class="picker-cap-icons">
      {#each model.capabilities as cap (cap)}
        <CapabilityIcon capability={cap} size={12} />
      {/each}
    </div>
  </div>
  <div class="picker-model-desc">{model.description}</div>
</button>

// src/frontend/react/components/ModelListItem.tsx
import { COST_LABELS, COST_COLORS, type ModelDef } from "../../models";
import { CapabilityIcon } from "./CapabilityIcon";

type ModelListItemProps = {
  model: ModelDef;
  onClick: () => void;
  providerLogoPath: string;
  selected: boolean;
};

export const ModelListItem = ({
  model,
  onClick,
  providerLogoPath,
  selected,
}: ModelListItemProps) => (
  <button
    className={`picker-model ${selected ? "selected" : ""}`}
    onClick={onClick}
    type="button"
  >
    <div className="picker-model-row">
      <img
        alt=""
        className="picker-model-logo"
        height="16"
        src={`${providerLogoPath}/${model.provider}.svg`}
        width="16"
      />
      <span className="picker-model-name">{model.name}</span>
      <span className="picker-cost" style={{ color: COST_COLORS[model.cost] }}>
        {COST_LABELS[model.cost]}
      </span>
      {model.legacy && <span className="picker-legacy">legacy</span>}
      <div className="picker-cap-icons">
        {model.capabilities.map((cap) => (
          <CapabilityIcon capability={cap} key={cap} size={12} />
        ))}
      </div>
    </div>
    <div className="picker-model-desc">{model.description}</div>
  </button>
);
