// src/frontend/vue/components/ModelListItem.vue
<script setup lang="ts">
import { COST_LABELS, COST_COLORS, type ModelDef } from "../../models";
import CapabilityIcon from "./CapabilityIcon.vue";

defineProps<{
  model: ModelDef;
  providerLogoPath: string;
  selected: boolean;
}>();

const emit = defineEmits<{
  click: [];
}>();
</script>

<template>
  <button
    :class="['picker-model', { selected }]"
    type="button"
    @click="emit('click')"
  >
    <div class="picker-model-row">
      <img
        alt=""
        class="picker-model-logo"
        height="16"
        :src="`${providerLogoPath}/${model.provider}.svg`"
        width="16"
      />
      <span class="picker-model-name">{{ model.name }}</span>
      <span class="picker-cost" :style="{ color: COST_COLORS[model.cost] }">
        {{ COST_LABELS[model.cost] }}
      </span>
      <span v-if="model.legacy" class="picker-legacy">legacy</span>
      <div class="picker-cap-icons">
        <CapabilityIcon
          v-for="cap in model.capabilities"
          :key="cap"
          :capability="cap"
          :size="12"
        />
      </div>
    </div>
    <div class="picker-model-desc">{{ model.description }}</div>
  </button>
</template>

// src/frontend/react/components/ModelListItem.tsx
import { COST_LABELS, COST_COLORS, type ModelDef } from "../../models";
import { CapabilityIcon } from "./CapabilityIcon";

type ModelListItemProps = {
  model: ModelDef;
  onClick: () => void;
  providerLogoPath: string;
  selected: boolean;
};

export const ModelListItem = ({
  model,
  onClick,
  providerLogoPath,
  selected,
}: ModelListItemProps) => (
  <button
    className={`picker-model ${selected ? "selected" : ""}`}
    onClick={onClick}
    type="button"
  >
    <div className="picker-model-row">
      <img
        alt=""
        className="picker-model-logo"
        height="16"
        src={`${providerLogoPath}/${model.provider}.svg`}
        width="16"
      />
      <span className="picker-model-name">{model.name}</span>
      <span className="picker-cost" style={{ color: COST_COLORS[model.cost] }}>
        {COST_LABELS[model.cost]}
      </span>
      {model.legacy && <span className="picker-legacy">legacy</span>}
      <div className="picker-cap-icons">
        {model.capabilities.map((cap) => (
          <CapabilityIcon capability={cap} key={cap} size={12} />
        ))}
      </div>
    </div>
    <div className="picker-model-desc">{model.description}</div>
  </button>
);
