// src/frontend/angular/components/chat-input.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
} from "@angular/core";
import { NgClass } from "@angular/common";
import type { ModelDef } from "../../models";
import {
  FilePreviewItemComponent,
  type PendingFile,
} from "./file-preview-item.component";
import { InputToolbarComponent } from "./input-toolbar.component";

@Component({
  imports: [NgClass, FilePreviewItemComponent, InputToolbarComponent],
  selector: "app-chat-input",
  standalone: true,
  template: `
    <form
      class="chat-input-card"
      [ngClass]="{ centered: !hasMessages }"
      (dragover)="onDragOver($event)"
      (dragleave)="onDragLeave($event)"
      (drop)="onDrop($event)"
      (submit)="onSubmit($event)"
    >
      @if (pendingFiles.length > 0) {
        <div class="file-previews">
          @for (file of pendingFiles; track $index) {
            <app-file-preview-item
              [file]="file"
              (remove)="removeFile.emit($index)"
            />
          }
        </div>
      }
      <textarea
        #textareaEl
        autocomplete="off"
        [disabled]="isStreaming"
        name="input"
        (keydown)="onKeyDown($event)"
        (paste)="onPaste($event)"
        [placeholder]="hasMessages ? 'Reply...' : 'Ask anything...'"
        [rows]="hasMessages ? 1 : 2"
      ></textarea>
      <input
        #fileInput
        [accept]="acceptTypes"
        multiple
        (change)="onFileChange($event)"
        style="display: none"
        type="file"
      />
      <app-input-toolbar
        [isStreaming]="isStreaming"
        [selectedModel]="selectedModel"
        [supportsAttachments]="supportsAttachments"
        [supportsVision]="supportsVision"
        [supportsPdf]="supportsPdf"
        (attachClick)="fileInput.click()"
        (cancel)="cancelStream.emit()"
        (selectModel)="selectModel.emit($event)"
      />
    </form>
  `,
})
export class ChatInputComponent {
  @Input() hasMessages = false;
  @Input() isStreaming = false;
  @Input() pendingFiles: PendingFile[] = [];
  @Input() selectedModel: ModelDef = {
    capabilities: [],
    cost: "free",
    description: "",
    id: "",
    name: "",
    provider: "openai",
  };
  @Input() supportsAttachments = false;
  @Input() supportsVision = false;
  @Input() supportsPdf = false;
  @Output() processFiles = new EventEmitter<FileList | File[]>();
  @Output() removeFile = new EventEmitter<number>();
  @Output() cancelStream = new EventEmitter<void>();
  @Output() selectModel = new EventEmitter<ModelDef>();
  @Output() submitMessage = new EventEmitter<string>();

  @ViewChild("fileInput") fileInput: ElementRef<HTMLInputElement> | undefined;
  @ViewChild("textareaEl") textareaEl:
    | ElementRef<HTMLTextAreaElement>
    | undefined;

  get acceptTypes() {
    const types: string[] = [];
    if (this.supportsVision) {
      types.push("image/png", "image/jpeg", "image/gif", "image/webp");
    }
    if (this.supportsPdf) {
      types.push("application/pdf");
    }

    return types.join(",");
  }

  onDragOver(evt: DragEvent) {
    evt.preventDefault();
    const target: HTMLElement =
      evt.currentTarget instanceof HTMLElement
        ? evt.currentTarget
        : document.createElement("div");
    target.classList.add("drag-over");
  }

  onDragLeave(evt: DragEvent) {
    const target: HTMLElement =
      evt.currentTarget instanceof HTMLElement
        ? evt.currentTarget
        : document.createElement("div");
    target.classList.remove("drag-over");
  }

  onDrop(evt: DragEvent) {
    evt.preventDefault();
    const target: HTMLElement =
      evt.currentTarget instanceof HTMLElement
        ? evt.currentTarget
        : document.createElement("div");
    target.classList.remove("drag-over");
    if (evt.dataTransfer?.files && evt.dataTransfer.files.length > 0) {
      this.processFiles.emit(evt.dataTransfer.files);
    }
  }

  onKeyDown(evt: KeyboardEvent) {
    if (evt.key !== "Enter" || evt.shiftKey) return;
    evt.preventDefault();
    const eventTarget = evt.target instanceof HTMLElement ? evt.target : null;
    const form = eventTarget?.closest("form");
    form?.requestSubmit();
  }

  onPaste(evt: ClipboardEvent) {
    const items = evt.clipboardData?.items;
    if (!items) return;
    const files: File[] = [];
    for (const item of Array.from(items)) {
      const isAttachable =
        item.type.startsWith("image/") || item.type === "application/pdf";
      if (!isAttachable) continue;
      const file = item.getAsFile();
      if (file) files.push(file);
    }
    if (files.length > 0) this.processFiles.emit(files);
  }

  onFileChange(evt: Event) {
    const input = evt.target instanceof HTMLInputElement ? evt.target : null;
    if (!input) return;
    if (input.files) this.processFiles.emit(input.files);
    input.value = "";
  }

  onSubmit(evt: Event) {
    evt.preventDefault();
    const textarea = this.textareaEl?.nativeElement;
    if (!textarea) return;
    const value = textarea.value.trim();
    if (!value) return;
    this.submitMessage.emit(value);
    textarea.value = "";
  }
}

// src/frontend/vue/components/ChatInput.vue
<script setup lang="ts">
import type { ModelDef } from "../../models";
import FilePreviewItem from "./FilePreviewItem.vue";
import InputToolbar from "./InputToolbar.vue";

type MediaType =
  | "image/png"
  | "image/jpeg"
  | "image/gif"
  | "image/webp"
  | "application/pdf";

type PendingFile = {
  data: string;
  media_type: MediaType;
  name: string;
  preview: string;
};

const props = defineProps<{
  fileInputRef: HTMLInputElement | null;
  hasMessages: boolean;
  isStreaming: boolean;
  pendingFiles: PendingFile[];
  selectedModel: ModelDef;
  supportsAttachments: boolean;
  supportsPdf: boolean;
  supportsVision: boolean;
}>();

const emit = defineEmits<{
  cancel: [];
  processFiles: [files: FileList | File[]];
  removeFile: [idx: number];
  selectModel: [model: ModelDef];
  submit: [evt: Event];
}>();

const onDragOver = (evt: DragEvent) => {
  evt.preventDefault();
  (evt.currentTarget as HTMLElement).classList.add("drag-over");
};

const onDragLeave = (evt: DragEvent) => {
  (evt.currentTarget as HTMLElement).classList.remove("drag-over");
};

const onDrop = (evt: DragEvent) => {
  evt.preventDefault();
  (evt.currentTarget as HTMLElement).classList.remove("drag-over");
  if (evt.dataTransfer?.files && evt.dataTransfer.files.length > 0) {
    emit("processFiles", evt.dataTransfer.files);
  }
};

const onKeyDown = (evt: KeyboardEvent) => {
  if (evt.key !== "Enter" || evt.shiftKey) return;
  evt.preventDefault();
  (evt.currentTarget as HTMLTextAreaElement).form?.requestSubmit();
};

const onPaste = (evt: ClipboardEvent) => {
  if (!evt.clipboardData) return;
  const { items } = evt.clipboardData;
  const files: File[] = [];
  for (const item of Array.from(items)) {
    const isAttachable =
      item.type.startsWith("image/") || item.type === "application/pdf";
    if (!isAttachable) continue;
    const file = item.getAsFile();
    if (file) files.push(file);
  }
  if (files.length > 0) emit("processFiles", files);
};
</script>

<template>
  <form
    :class="['chat-input-card', { centered: !hasMessages }]"
    @dragleave="onDragLeave"
    @dragover="onDragOver"
    @drop="onDrop"
    @submit.prevent="emit('submit', $event)"
  >
    <div v-if="pendingFiles.length > 0" class="file-previews">
      <FilePreviewItem
        v-for="(file, idx) in pendingFiles"
        :key="`${file.name}-${idx}`"
        :file="file"
        @remove="emit('removeFile', idx)"
      />
    </div>
    <textarea
      autocomplete="off"
      :disabled="isStreaming"
      name="input"
      :placeholder="hasMessages ? 'Reply...' : 'Ask anything...'"
      :rows="hasMessages ? 1 : 2"
      @keydown="onKeyDown"
      @paste="onPaste"
    />
    <InputToolbar
      :file-input-ref="fileInputRef"
      :is-streaming="isStreaming"
      :selected-model="selectedModel"
      :supports-attachments="supportsAttachments"
      :supports-pdf="supportsPdf"
      :supports-vision="supportsVision"
      @cancel="emit('cancel')"
      @select-model="(model: ModelDef) => emit('selectModel', model)"
    />
  </form>
</template>
